[project]
name = "productivity-bot"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "aiogram>=3.30.0",
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "httpx2>=2.10.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]==2.0.51",
    "uvicorn[standard]>=0.52.1",
]

[project.scripts]
productivity-bot = "productivity_bot.main:main"
productivity-bot-telegram-update-worker = "productivity_bot.telegram_update_worker:main"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
"" = "src"

[tool.mypy]
plugins = ["pydantic.mypy"]
